server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: Um9iZXJ0QDIyMDU=